# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    sync_code_signing(type: "appstore")
    build_app(scheme: "TryJenkins",
    		  workspace: "TryJenkins.xcworkspace",
    		  include_bitcode: true)
    increment_build_number(
    	build_number: latest_testflight_build_number + 1,
    	xcodeproj: "TryJenkins.xcodeproj"
  	)
    upload_to_testflight
    slack(message: "Successfully distribute a new beta build")
  end
end
